#  K Fold Cross Validation

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [3]:
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [6]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [7]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [8]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [11]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
get_score(SVC(), X_train, y_train, X_test, y_test)

0.9907407407407407

In [13]:
from sklearn.model_selection import StratifiedKFold

In [14]:
skf = StratifiedKFold(n_splits=3)

In [15]:
scores_lr = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),X_train, y_train, X_test, y_test))
    scores_svm.append(get_score(SVC(),X_train, y_train, X_test, y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train, y_train, X_test, y_test))

C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [16]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [17]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [18]:
scores_rf

[0.9348914858096828, 0.9565943238731218, 0.9215358931552587]

In [19]:
np.array(scores_lr).mean()

0.9265442404006677

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv = 3)

C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92153589, 0.94156928, 0.91652755])

In [22]:
cross_val_score(SVC(), digits.data, digits.target, cv = 3)

array([0.96494157, 0.97996661, 0.96494157])

# Parameter tuning

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv = 3)

array([0.91819699, 0.94323873, 0.92153589])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv = 3)

array([0.92988314, 0.94991653, 0.92153589])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=80), digits.data, digits.target, cv = 3)

array([0.93989983, 0.95993322, 0.93155259])

# Exercise

In [53]:
from sklearn.datasets import load_iris
iris = load_iris()

In [55]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [79]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2)

In [61]:
len(X_train)

120

In [63]:
len(X_test)

30

In [81]:
X_train[:5]

array([[5.8, 2.7, 3.9, 1.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.1, 3. , 4.9, 1.8],
       [7.6, 3. , 6.6, 2.1]])

In [83]:
iris_lr = LogisticRegression()
iris_lr.fit(X_train, y_train)
iris_lr.score(X_test, y_test)

0.9666666666666667

In [85]:
iris_svm = SVC()
iris_svm.fit(X_train, y_train)
iris_svm.score(X_test, y_test)

1.0

In [87]:
iris_rf = RandomForestClassifier(n_estimators=3)
iris_rf.fit(X_train, y_train)
iris_rf.score(X_test, y_test)

0.9333333333333333

In [93]:
cross_val_score(LogisticRegression(), iris.data, iris.target, cv = 3)

C:\Users\manas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [95]:
cross_val_score(SVC(), iris.data, iris.target, cv = 3)

array([0.96, 0.98, 0.94])

In [97]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv = 3)

array([0.98, 0.94, 0.98])