In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
file_path = "/content/drive/MyDrive/ML_Lab/cancer_data.csv"

In [3]:
import pandas as pd

df= pd.read_csv(file_path)
df.head()

Id  WBC_area  WBC_convex_area  WBC_peri   ecc_wbc  solidity_wbc  \
0   1     10073            10170   397.525  0.471852      0.990462   
1   2       450              450    83.916  0.866025      1.000000   
2   3     10349            10506   413.412  0.211948      0.985056   
3   4     10827            10862   401.949  0.215046      0.996778   
4   5      3421             3470   247.499  0.884772      0.985879   

   orient_wbc  nuc_area  nuc_ratio  peri_nuc  ...  avg_cyt_re  avg_cyt_gr  \
0   84.266745      7670   0.761441   344.139  ...  130.713275  123.667915   
1    0.000000       204   0.453333    82.255  ...  115.975610   67.243902   
2   -7.032837      8092   0.781911   327.046  ...  135.955693  129.935312   
3  -56.467459      8326   0.769003   355.255  ...  131.139544  122.655338   
4   -7.053928      2582   0.754750   217.886  ...  150.808105  142.667461   

   avg_cyt_bl  entropy_cyt   minoraxis   majoraxis  minoraxis_nuc  \
0  145.271328   -29.556808  108.497299  123.057794      90.427364   
1  140.126016    -3.650864   17.320508   34.641016      14.005658   
2  144.863093   -25.080685  116.237091  118.939275     100.504110   
3  143.148741   -29.023241  118.451811  121.289517     102.269262   
4  176.097735   -15.562377   46.218970   99.177380      41.875873   

   majoraxis_nuc  axismeanratio  Diagnosis  
0     108.957290       1.718868          M  
1      26.951812       1.586649          B  
2     102.755103       1.728577          M  
3     104.048451       1.721235          M  
4      85.638339       1.769519          M  

[5 rows x 24 columns]

## Mapping

# M -> 1
# B -> 0

In [4]:
df["Diagnosis"] = df["Diagnosis"].map(
    {
        "M" : 1,
        "B" : 0
    }
)
df.head()

Id  WBC_area  WBC_convex_area  WBC_peri   ecc_wbc  solidity_wbc  \
0   1     10073            10170   397.525  0.471852      0.990462   
1   2       450              450    83.916  0.866025      1.000000   
2   3     10349            10506   413.412  0.211948      0.985056   
3   4     10827            10862   401.949  0.215046      0.996778   
4   5      3421             3470   247.499  0.884772      0.985879   

   orient_wbc  nuc_area  nuc_ratio  peri_nuc  ...  avg_cyt_re  avg_cyt_gr  \
0   84.266745      7670   0.761441   344.139  ...  130.713275  123.667915   
1    0.000000       204   0.453333    82.255  ...  115.975610   67.243902   
2   -7.032837      8092   0.781911   327.046  ...  135.955693  129.935312   
3  -56.467459      8326   0.769003   355.255  ...  131.139544  122.655338   
4   -7.053928      2582   0.754750   217.886  ...  150.808105  142.667461   

   avg_cyt_bl  entropy_cyt   minoraxis   majoraxis  minoraxis_nuc  \
0  145.271328   -29.556808  108.497299  123.057794      90.427364   
1  140.126016    -3.650864   17.320508   34.641016      14.005658   
2  144.863093   -25.080685  116.237091  118.939275     100.504110   
3  143.148741   -29.023241  118.451811  121.289517     102.269262   
4  176.097735   -15.562377   46.218970   99.177380      41.875873   

   majoraxis_nuc  axismeanratio  Diagnosis  
0     108.957290       1.718868          1  
1      26.951812       1.586649          0  
2     102.755103       1.728577          1  
3     104.048451       1.721235          1  
4      85.638339       1.769519          1  

[5 rows x 24 columns]

In [5]:
X = df.drop(["Id", "Diagnosis"], axis = 1)
y = df["Diagnosis"]

In [6]:
X.head()

WBC_area  WBC_convex_area  WBC_peri   ecc_wbc  solidity_wbc  orient_wbc  \
0     10073            10170   397.525  0.471852      0.990462   84.266745   
1       450              450    83.916  0.866025      1.000000    0.000000   
2     10349            10506   413.412  0.211948      0.985056   -7.032837   
3     10827            10862   401.949  0.215046      0.996778  -56.467459   
4      3421             3470   247.499  0.884772      0.985879   -7.053928   

   nuc_area  nuc_ratio  peri_nuc  round_nuc  ...  convex_area_nuc  avg_cyt_re  \
0      7670   0.761441   344.139   0.813837  ...             7930  130.713275   
1       204   0.453333    82.255   0.378892  ...              312  115.975610   
2      8092   0.781911   327.046   0.950710  ...             8232  135.955693   
3      8326   0.769003   355.255   0.829022  ...             8593  131.139544   
4      2582   0.754750   217.886   0.683451  ...             2627  150.808105   

   avg_cyt_gr  avg_cyt_bl  entropy_cyt   minoraxis   majoraxis  minoraxis_nuc  \
0  123.667915  145.271328   -29.556808  108.497299  123.057794      90.427364   
1   67.243902  140.126016    -3.650864   17.320508   34.641016      14.005658   
2  129.935312  144.863093   -25.080685  116.237091  118.939275     100.504110   
3  122.655338  143.148741   -29.023241  118.451811  121.289517     102.269262   
4  142.667461  176.097735   -15.562377   46.218970   99.177380      41.875873   

   majoraxis_nuc  axismeanratio  
0     108.957290       1.718868  
1      26.951812       1.586649  
2     102.755103       1.728577  
3     104.048451       1.721235  
4      85.638339       1.769519  

[5 rows x 22 columns]

In [7]:
y[:5]

0    1
1    0
2    1
3    1
4    1
Name: Diagnosis, dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:5]

array([[ 0.50646876,  0.50563813,  0.57847107, -0.32554849,  0.32610164,
         1.57434138,  0.60431151,  0.55413699,  0.38118481,  0.76924137,
        -0.00870345,  0.62792245,  0.52283796,  0.11932716,  0.48010193,
         0.00374397, -0.57973783,  0.58951251,  0.44448733,  0.58443297,
         0.46098038,  0.01613218],
       [-1.64036804, -1.65215377, -2.19642359,  1.19705509,  1.19385378,
        -0.04969887, -1.67023463, -2.46503116, -2.18063568, -1.41101276,
         1.02468555, -2.17735424, -1.6839212 , -0.83297784, -1.60644022,
        -0.26215721,  1.88422366, -1.77574438, -2.40979872, -1.88035557,
        -2.37037199, -2.14807013],
       [ 0.5680428 ,  0.58022847,  0.71904341, -1.32950221, -0.16573308,
        -0.18524   ,  0.73287546,  0.75472184,  0.21397644,  1.45534607,
        -1.22743701,  0.76918661,  0.61032041,  0.45807695,  0.71186829,
        -0.01735294, -0.15400562,  0.79029383,  0.31153257,  0.90943286,
         0.24684131,  0.17504083],
       [ 0.67468189

## SOM

In [10]:
!pip install sklearn-som

In [11]:
from sklearn_som.som import SOM

In [12]:
X_scaled.shape

(10, 22)

In [13]:
som = SOM(m=10, n=10, dim = X_scaled.shape[1], random_state = 42)
som.fit(X_scaled)

In [14]:
X_som = som.transform(X_scaled)
X_som

array([[ 2.20673294,  1.98558694,  1.38530345,  3.72351216,  5.56703813,
         5.16663374,  5.91484625,  5.71522146,  4.83912812,  4.85955499,
         3.61494415,  1.87346737,  2.83657546,  5.40417478,  5.22874806,
         5.4848088 ,  4.14360847,  5.68645977,  5.00086327,  5.7385819 ,
         5.08860781,  4.83367679,  6.33011846,  5.31657055,  5.22497561,
         5.14637657,  6.00626308,  5.87392263,  6.1327322 ,  5.24675543,
         7.03858615,  5.5422014 ,  5.98309047,  5.28569461,  4.8931031 ,
         4.93741039,  4.20674302,  6.48397597,  5.13959218,  5.45295589,
         5.8844519 ,  6.23919434,  3.59614396,  6.57148358,  4.44075019,
         4.25222951,  5.49353295,  4.71216265,  4.85138142,  4.50657953,
         4.78294109,  6.17279261,  5.06717751,  6.26399975,  5.53923204,
         6.66297391,  5.02563626,  4.58289807,  6.43627329,  6.56242132,
         5.34583393,  5.36084641,  6.4342381 ,  4.34528746,  5.00929377,
         6.59686568,  4.69597338,  3.58805035,  5.3

In [15]:
X_som.shape

(10, 100)

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(C=0.1, max_iter = 1000)
model.fit(X_som,y)

LogisticRegression(C=0.1, max_iter=1000)

In [19]:
som_score = model.score(X_som, y)
som_score

0.9

## Q-learning

In [35]:
from sklearn.cluster import KMeans

kmean = KMeans(n_clusters = 5, n_init = 10, random_state = 42)
states = kmean.fit_predict(X_scaled)
states

array([0, 1, 0, 0, 3, 0, 2, 3, 4, 0], dtype=int32)

In [37]:
import numpy as np

n_states = 5
n_actions = 2

# Initialize q-table with zeroes
q_table = np.zeros((n_states, n_actions))

# Q-learning parameter
learning_rate = 0.1
epsilon = 0.2
n_epochs = 1000

q_table

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
import random

y_np = y.to_numpy()

for epoch in range(n_epochs):
  for i in range(len(X_scaled)):
    # Get current state and true label
    state = states[i]
    true_label = y_np[i]

    # Epsilon-greedy action selection
    if random.uniform(0,1) < 0.1:
      action = random.choice([0,1])
    else:
      action = np.argmax(q_table[state])

    # Reward
    if action == true_label:
      reward = 1
    else:
      reward = -1

    # Update q-table
    old_value = q_table[state,action]
    new_value = old_value + learning_rate * (reward-old_value)
    q_table[state,action] = new_value

print("Q-learning Complete")
print(f"Q-table:\n{q_table}")

Q-learning Complete
Q-table:
[[-0.30364817  0.07018377]
 [ 1.         -0.98802748]
 [ 1.         -0.99127204]
 [-0.99998857  1.        ]
 [-0.99753497  1.        ]]


In [39]:
y_pred = []

for i in range(len(X_scaled)):
  state = states[i]
  prediction = np.argmax(q_table[state])
  y_pred.append(prediction)

y_pred

[np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1)]