# NumPy Documentation (My Version)

- Numpy is used in scientific computing. (use of computers to solve scientific and engineering problems that involve complex mathematics)
- It makes math and data processing faster and easier, especially when working with large amounts of data.

In [5]:
import numpy as np

In [6]:
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [7]:
list1[0]

1

In [8]:
list2 = ["Manash Nepal" , 22, list1, True]
list2

['Manash Nepal', 22, [1, 2, 3, 4], True]

In [9]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
type(np1)

numpy.ndarray

In [11]:
type(np1[0])

numpy.int32

In [12]:
np.shape(np1)

(10,)

In [13]:
# arange
np2 = np.arange(start=0,stop=5.5,step=0.5)
print(np2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [14]:
# zeros
np3 = np.zeros(2, dtype=int)
np3

array([0, 0])

In [15]:
np4 = np.zeros((2,3), dtype=int)
print(np4)

[[0 0 0]
 [0 0 0]]


In [16]:
np5 = np.array([[2,3],[3,4]])
np5

array([[2, 3],
       [3, 4]])

In [17]:
np6 = np.full((2,3),fill_value=10)
np6

array([[10, 10, 10],
       [10, 10, 10]])

In [18]:
np7 = np.full(10,10)
np7

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [19]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [20]:
np8 = np.array(my_list)
np8

array([1, 2, 3, 4, 5])

In [21]:
type(np8)

numpy.ndarray

# Slicing numpy arrays

In [23]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
np1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Basic slicing
np1[1:5]

array([1, 2, 3, 4])

In [25]:
my_list = [1,2,3,4,5]
my_list[1:5]

[2, 3, 4, 5]

In [26]:
# Slicing from some index till end
np1[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np1[-1:-7:-1]

array([10,  9,  8,  7,  6,  5])

In [28]:
np1[1:6:2]

array([1, 3, 5])

In [29]:
np1[::2]

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np1[1::2]

array([1, 3, 5, 7, 9])

In [31]:
# Slicing 2D array
np2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
np2[1][2]

8

In [32]:
np2[0:2,1:3]

array([[2, 3],
       [7, 8]])

# Universal Function

In [62]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np2 = np.sqrt(np1)
for num in np2:
    print(num)

0.0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0


In [76]:
np2 = np.array([-3,-2,-1,0,1,2,3])
np2

array([-3, -2, -1,  0,  1,  2,  3])

In [78]:
np.absolute(np2)

array([3, 2, 1, 0, 1, 2, 3])

In [80]:
np.exp(np1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.min(np1)

0

In [84]:
np.max(np1)

9

In [88]:
np.sign(np2)

array([-1, -1, -1,  0,  1,  1,  1])

In [96]:
np.sin(np1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [98]:
np.cos(np1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [100]:
np.log(np1)

C:\Users\manas\AppData\Local\Temp\ipykernel_5512\3977740415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(np1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [106]:
np3 = np.array([1,2,3])
np4 = np.array([4,5,6])
np.add(np3,np4)

array([5, 7, 9])

In [110]:
np.fmod(np3,np4)

array([1, 2, 3])

In [116]:
np.greater(np4,np3)

array([ True,  True,  True])